### ISSUE TITLE
How to switch language dynamically : MVC architecture

### ISSUE THREAD

**Issue by SumanBhowmick** [elmasse/elmasse-bundle#24]
Hi,

My app is based on simple MVC architecture. 

How do I change the language dynamically in the controller?
 
I find that the latest elmasse-bundle(version 1.1.0) examples are based on MVVM architecture.

Thanks In advance.

**Comment by elmasse** [comment]
Hi @SumanBhowmick 
Yes, examples are using the MVVM architecture since its nature allows to use the 2 way bindings to avoid refreshing the application when changing locales.
Right now I cannot think of a "good way" to change locales on the fly using MVC alone. 
I'm open to discuss any approach you might want to follow if that helps.

My $0.02 
Max
